# Default configuration for Livestream Splitter

output:
  directory: "./segments"
  format: "mp4"
  naming_pattern: "{title}_part{index:02d}_{date}"
  max_segment_length: 1200  # 20 minutes in seconds

intro_outro:
  intro_path: null
  outro_path: null

processing:
  quality: "high"
  codec: "h264"
  preset: "medium"
  crf: 23
  threads: 4